### ISSUE TITLE
Error al publicar Reportes

### ISSUE THREAD

**Issue by diegocrzt** [TEDICpy/miciudad2#24]
**Comportamiento esperado**

Al publicar reclamos el proceso finaliza correctamente y se muestra el listado de reclamos

**Comportamiento observado**

Aparece una pantalla de error indicando que ocurrió un problema en el backend 

**OBS:** Este comportamiento puede ser afectado por los cambios en #23 , por lo que es mejor resolver primero el flujo de los reclamos y luego verificar este comportamiento.

**Información adicional**

Logs
```
I, [2018-05-29T09:26:37.608009 #13370]  INFO -- : [0bc83e42-5614-4a9d-bc9d-17b89ede7c64] Completed 500 Internal Server Error in 12ms (ActiveRecord: 0.8ms)
F, [2018-05-29T09:26:37.610862 #13370] FATAL -- : [0bc83e42-5614-4a9d-bc9d-17b89ede7c64]   
F, [2018-05-29T09:26:37.610996 #13370] FATAL -- : [0bc83e42-5614-4a9d-bc9d-17b89ede7c64] NoMethodError (undefined method `published?' for nil:NilClass):
F, [2018-05-29T09:26:37.611059 #13370] FATAL -- : [0bc83e42-5614-4a9d-bc9d-17b89ede7c64]   
F, [2018-05-29T09:26:37.611162 #13370] FATAL -- : [0bc83e42-5614-4a9d-bc9d-17b89ede7c64] /usr/local/rvm/gems/ruby-2.4.1/bundler/gems/decidim-reclamos-d8507b24169c/app/commands/decidim/denuncias/admin/publish_denuncia.rb:25:in `call'
[0bc83e42-5614-4a9d--17b89ede7c64] rectify (0.11.0) lib/rectify/command.rb:30:in `call'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] /usr/local/rvm/gems/ruby-2.4.1/bundler/gems/decidim-reclamos-d8507b24169c/app/controllers/decidim/denuncias/admin/denuncias_controller.rb:75:in `publish'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] actionpack (5.1.6) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] actionpack (5.1.6) lib/abstract_controller/base.rb:186:in `process_action'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] actionpack (5.1.6) lib/action_controller/metal/rendering.rb:30:in `process_action'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] actionpack (5.1.6) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] activesupport (5.1.6) lib/active_support/callbacks.rb:131:in `run_callbacks'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] actionpack (5.1.6) lib/abstract_controller/callbacks.rb:19:in `process_action'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] actionpack (5.1.6) lib/action_controller/metal/rescue.rb:20:in `process_action'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] actionpack (5.1.6) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] activesupport (5.1.6) lib/active_support/notifications.rb:166:in `block in instrument'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] activesupport (5.1.6) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] activesupport (5.1.6) lib/active_support/notifications.rb:166:in `instrument'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] actionpack (5.1.6) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] actionpack (5.1.6) lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] activerecord (5.1.6) lib/active_record/railties/controller_runtime.rb:22:in `process_action'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] actionpack (5.1.6) lib/abstract_controller/base.rb:124:in `process'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] actionview (5.1.6) lib/action_view/rendering.rb:30:in `process'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] actionpack (5.1.6) lib/action_controller/metal.rb:189:in `dispatch'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] actionpack (5.1.6) lib/action_controller/metal.rb:253:in `dispatch'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] actionpack (5.1.6) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] actionpack (5.1.6) lib/action_dispatch/routing/route_set.rb:31:in `serve'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] actionpack (5.1.6) lib/action_dispatch/journey/router.rb:50:in `block in serve'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] actionpack (5.1.6) lib/action_dispatch/journey/router.rb:33:in `each'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] actionpack (5.1.6) lib/action_dispatch/journey/router.rb:33:in `serve'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] actionpack (5.1.6) lib/action_dispatch/routing/route_set.rb:844:in `call'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] railties (5.1.6) lib/rails/engine.rb:522:in `call'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] railties (5.1.6) lib/rails/railtie.rb:185:in `public_send'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] railties (5.1.6) lib/rails/railtie.rb:185:in `method_missing'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] actionpack (5.1.6) lib/action_dispatch/routing/mapper.rb:17:in `block in <class:Constraints>'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] actionpack (5.1.6) lib/action_dispatch/routing/mapper.rb:46:in `serve'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] actionpack (5.1.6) lib/action_dispatch/journey/router.rb:50:in `block in serve'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] actionpack (5.1.6) lib/action_dispatch/journey/router.rb:33:in `each'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] actionpack (5.1.6) lib/action_dispatch/journey/router.rb:33:in `serve'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] actionpack (5.1.6) lib/action_dispatch/routing/route_set.rb:844:in `call'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] railties (5.1.6) lib/rails/engine.rb:522:in `call'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] railties (5.1.6) lib/rails/railtie.rb:185:in `public_send'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] railties (5.1.6) lib/rails/railtie.rb:185:in `method_missing'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] actionpack (5.1.6) lib/action_dispatch/routing/mapper.rb:17:in `block in <class:Constraints>'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] actionpack (5.1.6) lib/action_dispatch/routing/mapper.rb:46:in `serve'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] actionpack (5.1.6) lib/action_dispatch/journey/router.rb:50:in `block in serve'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] actionpack (5.1.6) lib/action_dispatch/journey/router.rb:33:in `each'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] actionpack (5.1.6) lib/action_dispatch/journey/router.rb:33:in `serve'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] actionpack (5.1.6) lib/action_dispatch/routing/route_set.rb:844:in `call'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] railties (5.1.6) lib/rails/engine.rb:522:in `call'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] railties (5.1.6) lib/rails/railtie.rb:185:in `public_send'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] railties (5.1.6) lib/rails/railtie.rb:185:in `method_missing'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] actionpack (5.1.6) lib/action_dispatch/routing/mapper.rb:17:in `block in <class:Constraints>'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] actionpack (5.1.6) lib/action_dispatch/routing/mapper.rb:46:in `serve'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] actionpack (5.1.6) lib/action_dispatch/journey/router.rb:50:in `block in serve'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] actionpack (5.1.6) lib/action_dispatch/journey/router.rb:33:in `each'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] actionpack (5.1.6) lib/action_dispatch/journey/router.rb:33:in `serve'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] actionpack (5.1.6) lib/action_dispatch/routing/route_set.rb:844:in `call'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] decidim-core (0.10.1) app/middleware/decidim/current_organization.rb:21:in `call'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] omniauth (1.8.1) lib/omniauth/strategy.rb:190:in `call!'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] omniauth (1.8.1) lib/omniauth/strategy.rb:168:in `call'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] omniauth (1.8.1) lib/omniauth/strategy.rb:190:in `call!'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] omniauth (1.8.1) lib/omniauth/strategy.rb:168:in `call'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] omniauth (1.8.1) lib/omniauth/strategy.rb:190:in `call!'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] omniauth (1.8.1) lib/omniauth/strategy.rb:168:in `call'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] warden (1.2.7) lib/warden/manager.rb:35:in `catch'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] warden (1.2.7) lib/warden/manager.rb:35:in `call'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] rack (2.0.5) lib/rack/etag.rb:25:in `call'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] rack (2.0.5) lib/rack/conditional_get.rb:38:in `call'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] rack (2.0.5) lib/rack/head.rb:12:in `call'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] rack (2.0.5) lib/rack/session/abstract/id.rb:232:in `context'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] rack (2.0.5) lib/rack/session/abstract/id.rb:226:in `call'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] actionpack (5.1.6) lib/action_dispatch/middleware/cookies.rb:613:in `call'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] actionpack (5.1.6) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] activesupport (5.1.6) lib/active_support/callbacks.rb:97:in `run_callbacks'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] actionpack (5.1.6) lib/action_dispatch/middleware/callbacks.rb:24:in `call'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] actionpack (5.1.6) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] actionpack (5.1.6) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] railties (5.1.6) lib/rails/rack/logger.rb:36:in `call_app'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] railties (5.1.6) lib/rails/rack/logger.rb:24:in `block in call'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] activesupport (5.1.6) lib/active_support/tagged_logging.rb:69:in `block in tagged'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] activesupport (5.1.6) lib/active_support/tagged_logging.rb:26:in `tagged'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] activesupport (5.1.6) lib/active_support/tagged_logging.rb:69:in `tagged'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] railties (5.1.6) lib/rails/rack/logger.rb:24:in `call'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] actionpack (5.1.6) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] request_store (1.4.1) lib/request_store/middleware.rb:19:in `call'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] actionpack (5.1.6) lib/action_dispatch/middleware/request_id.rb:25:in `call'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] rack (2.0.5) lib/rack/method_override.rb:22:in `call'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] rack (2.0.5) lib/rack/runtime.rb:22:in `call'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] activesupport (5.1.6) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] actionpack (5.1.6) lib/action_dispatch/middleware/executor.rb:12:in `call'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] rack (2.0.5) lib/rack/sendfile.rb:111:in `call'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] rack-cors (1.0.2) lib/rack/cors.rb:97:in `call'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] railties (5.1.6) lib/rails/engine.rb:522:in `call'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] passenger (5.2.3) src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] passenger (5.2.3) src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:160:in `accept_and_process_next_request'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] passenger (5.2.3) src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
[0bc83e42-5614-4a9d-bc9d-17b89ede7c64] passenger (5.2.3) src/ruby_supportlib/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
[0bc83e42-5614-4a9d-bc9d-] passenger (5.2.3) src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
I, [2018-05-29T09:26:37.614646 #13370]  INFO -- : [0bc83e42-5614-4a9d-bc9d-17b89ede7c64] Processing by Decidim::ErrorsController#internal_server_error as HTML
I, [2018-05-29T09:26:37.614780 #13370]  INFO -- : [0bc83e424a9d-bc9d-17b89ede7c64]   Parameters: {"authenticity_token"=>"", "slug"=>"i-1"}
```

**Comment by diegocrzt** [comment]
Dado el cambio en #23 , este error no se presenta más, pues los reportes son publicados automáticamente
